---
apiVersion: v1
kind: Service
metadata:
  name: mango-admin
  labels:
    app: mango-admin
    service: mango-admin
spec:
  ports:
  - port: 8000
    name: http
    protocol: TCP
  selector:
    app: mango-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango-admin-v1
  labels:
    app: mango-admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango-admin
      version: v1
  template:
    metadata:
      labels:
        app: mango-admin
        version: v1
    spec:
      containers:
      - name: mango-admin
        image: registry.cn-shanghai.aliyuncs.com/mango-admin-team/mango-admin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: mango-admin
          mountPath: /temp
        - name: mango-admin
          mountPath: /static
        - name: mango-admin-config
          mountPath: /config/
          readOnly: true
      volumes:
      - name: mango-admin
        persistentVolumeClaim:
          claimName: mango-admin
      - name: mango-admin-config
        configMap:
          name: settings-admin
---
